mysql:
  host: "127.0.0.1"
  port: "3306"
  database: "server_anarchy?autoReconnect=true§useSSL=false"
  username: "root"
  password: "root"

mainWorld: 'world'

modules:
  hologram: true
  home: true
  customFlags: true
  regionSUI: false
  menu: true

Region:
  EMERALD_ORE:
    char: 'E'
    radius:
      X: 14
      Y: 14
      Z: 14
    place-sound: BLOCK_BEACON_ACTIVATE
    break-sound: BLOCK_BEACON_DEACTIVATE
  DIAMOND_BLOCK:
    char: 'D'
    radius:
      X: 14
      Y: 14
      Z: 14
    place-sound: BLOCK_BEACON_ACTIVATE
    break-sound: BLOCK_BEACON_DEACTIVATE
  IRON_BLOCK:
    char: 'I'
    radius:
      X: 14
      Y: 14
      Z: 14
    place-sound: BLOCK_BEACON_ACTIVATE
    break-sound: BLOCK_BEACON_DEACTIVATE

language:
  cantProtectThat: '§cВы не можете защитить эту область.'
  protected: 'Эта территория теперь защищена.'
  cantPutRegionInAnotherRegion: 'Нельзя поставить регион, в другой регион'
  inprotected: '§cВы убрали защиту'
  help:
    - 'Команды:'
    - '§c/rg info <Регион>'
    - '§c/rg remove <Регион> <Игрок>'
    - '§c/rg addmember <Регион> <Игрок>'
    - '§c/rg addowner <Регион> <Игрок>'
    - '§c/rg sethome'
    - '§c/rg home <Регион>'
    - '§c/rg list'
  info:
    - 'Информация о регионе:'
    - 'Название региона: %region_id%'
    - 'Владельцы: %region_owners%'
    - 'Участники: %region_members%'
  noRegionWithName: 'Нет региона с именем %region_id%'
  correctUseInfo: 'В вашей области нет региона используйте, /rg info <Регион>'
  correctUse:
    remove:
      1: 'Используйте: /rg remove <Регион> <Игрок>'
      2: 'Регион %region_id% не существует'
      3: 'Вы не являетесь владельцем региона %region_id%'
      4: 'Используйте: /rg remove %region_id% <Игрок>'
      5: 'Игрока не существует'
      6: 'Игрок не в вашем регионе'
      7: 'Вы не можете удалить себя'
      8: 'Вы успешно удалили игрока %player_name%'
    addMember:
      1: 'Используйте: /rg addmember <Регион> <Игрок>'
      2: 'Регион %region_id% не существует'
      3: 'Вы не являетесь владельцем региона %region_id%'
      4: 'Используйте: /rg addmember %region_id% <Игрок>'
      5: 'Игрока не существует'
      6: 'Вы не можете удалить себя'
      7: 'Игрок уже в вашем регионе'
      8: 'Вы успешно добавили игрока'
    addOwner:
      1: 'Используйте: /rg addowner <Регион> <Игрок>'
      2: 'Регион %region_id% не существует'
      3: 'Вы не являетесь владельцем региона %region_id%'
      4: 'Используйте: /rg addowner %region_id% <Игрок>'
      5: 'Игрока не существует'
      6: 'Вы не можете удалить себя'
      7: 'Игрок уже в вашем регионе'
      8: 'Вы успешно добавили игрока'