mysql:
  host: "127.0.0.1"
  port: "3306"
  database: "server_anarchy?autoReconnect=true&useSSL=false"
  username: "root"
  password: "root"

mainWorld: 'world'

modules:
  hologram: true
  home: true
  customFlags: true
  regionSUI: false
  menu: true

Region:
  RED_MUSHROOM_BLOCK:
    char: 'RM'
    radius:
      X: 33
      Y: 33
      Z: 33
    place-sound: ENTITY_SHULKER_TELEPORT
    break-sound: ENTITY_SHULKER_OPEN
    place-effect:
      name: DRAGON_BREATH
      count: 100
  BROWN_MUSHROOM_BLOCK:
    char: 'BM'
    radius:
      X: 22
      Y: 22
      Z: 22
    place-sound: ENTITY_SHULKER_TELEPORT
    break-sound: ENTITY_SHULKER_OPEN
    place-effect:
      name: DRAGON_BREATH
      count: 100
  EMERALD_ORE:
    char: 'E'
    radius:
      X: 22
      Y: 22
      Z: 22
    place-sound: ENTITY_EXPERIENCE_ORB_PICKUP
    break-sound: BLOCK_ANVIL_PLACE
    place-effect:
      name: EXPLOSION_NORMAL
      count: 10
  DIAMOND_BLOCK:
    char: 'D'
    radius:
      X: 17
      Y: 17
      Z: 17
    place-sound: ENTITY_EXPERIENCE_ORB_PICKUP
    break-sound: BLOCK_ANVIL_PLACE
    place-effect:
      name: EXPLOSION_NORMAL
      count: 10
  IRON_BLOCK:
    char: 'I'
    radius:
      X: 8
      Y: 8
      Z: 8
    place-sound: ENTITY_EXPERIENCE_ORB_PICKUP
    break-sound: BLOCK_ANVIL_PLACE
    place-effect:
      name: EXPLOSION_NORMAL
      count: 70

language:
  cantProtectThat: '§fВы §cне можете §fзащитить эту область'
  protected: '§fЭта территория теперь §aзащищена§f!'
  cantPutRegionInAnotherRegion: '§fВы §cне можете §fустановить блок привата здесь! Ваш регион §bпересекается §fс другим'
  inprotected: '§fВы §cсломали §fблок привата! Теперь ваша территория §cне защищена'
  help:
    - ''
    - '  §e§lКоманды приватов на Анархии'
    - ''
    - '  §fИнформация о регионе §7– §a/rg info регион '
    - '  §fИсключить игрока §7– §a/rg remove регион игрок'
    - '  §fДобавить участника §7– §a/rg addmember регион игрок'
    - '  §fДобавить владельца §7– §a/rg addowner регион игрок'
    - '  §fУстановить точку дома §7– §a/rg sethome'
    - '  §fТелепортироваться домой §7– §a/rg home регион'
    - '  §fСписок регионов §7– §a/rg list'
    - ''
  info:
    - ''
    - '§e§lИнформация о регионе:'
    - ''
    - '§fНазвание региона: §a%region_id%'
    - '§fВладельцы: §a%region_owners%'
    - '§fУчастники: §a%region_members%'
    - ''
  noRegionWithName: '§cНет §fрегиона с именем §a%region_id%'
  correctUse:
    remove:
      1: '§fИспользуйте: §a/rg remove регион игрок'
      2: '§fРегион §a%region_id% §fне существует'
      3: '§fВы §cне являетесь §fвладельцем региона §a%region_id%'
      4: '§fИспользуйте: §a/rg remove %region_id% игрок'
      5: '§fИгрока с таким ником §cне существует'
      6: '§fИгрок, с данным ником, §cне состоит §fв вашем регионе'
      7: '§fВы §cне можете §fудалить себя'
      8: '§fВы успешно §cудалили §fигрока &a%player_name%'
    addMember:
      1: '§fИспользуйте: §a/rg addmember регион игрок'
      2: '§fРегион §a%region_id% §fне существует'
      3: '§fВы §cне являетесь §fвладельцем региона §a%region_id%'
      4: '§fИспользуйте: §a/rg addmember %region_id% игрок'
      5: '§fИгрока с таким ником §cне существует'
      6: '§fВы §cне можете §fдобавить себя'
      7: '§fИгрок, с данным ником, §aуже есть §fв вашем регионе'
      8: '§fВы успешно §aдобавили §fигрока'
    addOwner:
      1: '§fИспользуйте: §a/rg addowner регион игрок'
      2: '§fРегион §a%region_id% §fне существует'
      3: '§fВы §cне являетесь §fвладельцем региона §a%region_id%'
      4: '§fИспользуйте: §a/rg addowner %region_id% игрок'
      5: '§fИгрока с таким ником §cне существует'
      6: '§fВы §cне можете §fдобавить себя'
      7: '§fИгрок, с данным ником, §aуже есть §fв вашем регионе'
      8: '§fВы успешно §aдобавили §fигрока'